### ISSUE TITLE
Provide utility function to print time

### ISSUE THREAD

**Issue by chunghha** [noemi-salaun/ng-logger#13]
This is a feature request.

I like to have a function to print time like 
`blah blah log: {...} @ 07:38:55.814`

by
`export function logTime(time?: Date): string`

used in 
`this.logger.log(`blah blah log: ${JSON.stringify(res)}`, `${logTime(new Date())}`);`

@noemi-salaun if you think this is going to be useful then I will open a PR for this request.

**Comment by noemi-salaun** [comment]
I think this functionnality is out of the scope of this logger. The main purpose is to enable logging for specific level, with complete integration in Angular injection system.

Your fonctionnality can be implemented out of this lib, and then used in any strings.

Once again, thank you for your interest :smile:

**Comment by chunghha** [comment]
@noemi-salaun I see your point. On the other hand, I thought putting the utility function into this library so others don't need to repeat same code if they need it. But, it's your call so I appreciate you mentioned your point clearly, that's helpful to me.
