### ISSUE TITLE
[Question] Angular 4 -> 5 migration pitfalls

### ISSUE THREAD

**Issue by Kamilius** [noemi-salaun/ng-logger#15]
Hi @noemi-salaun, could you please describe what have you actually did to make your library `ng5 compatible`?
I'm trying to upgrade my `ng4.3.x` library to `5th` but it causes errors, which it previously didn't, without any "tips" on how to solve'em.

Thanks in advance

**Comment by noemi-salaun** [comment]
Hello,

Same as you, I was not able to make it work... So I migrate my build process to use the https://github.com/robisim74/angular-library-starter and it works great.

**Comment by Kamilius** [comment]
Ok. Could you tell what issues (if you remember) have you had with it?
Mine is that upon successful AOT build, while trying to use it inside of consuming application, started getting `Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.`.

**Comment by noemi-salaun** [comment]
Same thing. The app was not able to find the module of the library. I'm sorry this won't really help you :cry:
