### ISSUE TITLE
Color?

### ISSUE THREAD

**Issue by markterrill** [noemi-salaun/ng-logger#7]
Any ideas on how to smoothly implement color?

Very simple different colors for the different levels..

**Comment by noemi-salaun** [comment]
Console like Google Chrome Developer Tools already have colors depending on levels.
```javascript
console.error('Some error message');
```
will print _"Some error message"_ in red with the call stack trace, ...

My logger is only an alias for `console.xxx()`, so it keeps the same behavior.

If you want to add color in bash console, with node server or something else, I think you can use package like [colors](https://www.npmjs.com/package/colors) and use it with the `ng-logger`, but I'm not sure if it's compatible.
