### ISSUE TITLE
Log level debug is ignored

### ISSUE THREAD

**Issue by samized** [noemi-salaun/ng-logger#8]
Hi

Thanks for this logger library.
I have some problems with the log level DEBUG. All calls of `logger.debug(...)` seems to be ignored.

My Configuration
```
NgLoggerModule.forRoot(Level.LOG)
```

Test logging on all different levels in `AppComponent`
```
  ngOnInit() {
    this.logger.error('This is a priority level 1 error message...');
    this.logger.warn('This is a priority level 2 warning message...');
    this.logger.info('This is a priority level 3 warning message...');
    this.logger.debug('This is a priority level 4 debug message...');
    this.logger.log('This is a priority level 5 log message...');
  }
```

Output Console:
```
This is a priority level 1 error message... (red)
This is a priority level 2 warning message... (yellow)
This is a priority level 3 warning message...
This is a priority level 5 log message...
```

I use Angular 2.4.10

Thanks for your help.

**Comment by noemi-salaun** [comment]
Hello

Thanks for your interest :blush:

I created a [**plunker**](https://plnkr.co/edit/pcDXvNS7iwLYvvczzzv9?p=preview) to try to reproduce your error but it works just fine :grimacing:

You can select packages versions in the **config.js** file.

Make sure you don't filter the console. At first, I was filtering at `info` level with Chrome filter. Select `verbose` to see all levels.

**Comment by samized** [comment]
Thanks for the tip about Chrome's filter level, that was the problem ;)
